plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }

    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }

        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // Menu Menu
    implementation "com.terraformersmc:modmenu:${project.modmenu_version}"

    /********** Fabulously Optimized **********/

    // Animatica Refrabicated
    implementation "maven.modrinth:animaticarefabricated:0.6.2+26.1"

    // Better Block Entities
    implementation "maven.modrinth:better-block-entities:1.3.4+mc26.1.2"

    // Better Mount HUD
    implementation "maven.modrinth:better-mount-hud:1.3.0"

    // Better Grassify
    implementation "maven.modrinth:bettergrassify:1.8.6+fabric.26.1.2"

    // Cape Provider
    implementation "maven.modrinth:cape-provider:5.4.0"

    // Cloth Config
    implementation "maven.modrinth:cloth-config:26.1.154+fabric"

    // Config Manager
    implementation "maven.modrinth:configmanager:1.1.2"

    // Continuity
    implementation "maven.modrinth:continuity:3.0.1-beta.2+26.1"

    // Controlify
    implementation "maven.modrinth:controlify:3.0.1"

    // Crash Assistant
    implementation "maven.modrinth:crash-assistant:zDcQ7aOP"

    // Cubes Without Borders
    implementation "maven.modrinth:cubes-without-borders:4.0.5+26.1"

    // Debugify
    implementation "maven.modrinth:debugify:26.1.2.2"

    // Dynamic FPS
    implementation "maven.modrinth:dynamic-fps:3.11.7"

    // e4mc
    implementation "maven.modrinth:e4mc:6.1.0-fabric-modern"

    // Entity Model Features
    implementation "maven.modrinth:entity-model-features:3.2.4-fabric-26.1"

    // Entity Texture Features
    implementation "maven.modrinth:entitytexturefeatures:7.1-fabric-26.1"

    // Entity Culling
    implementation "maven.modrinth:entityculling:1.10.2"

    // Fabric Language Kotlin
    implementation "maven.modrinth:fabric-language-kotlin:1.13.11+kotlin.2.3.21"

    // Fabrishot
    implementation "maven.modrinth:fabrishot:1.17.0"

    // FastQuit
    implementation "maven.modrinth:fastquit:3.1.4+mc26.1.x"

    // FerriteCore
    implementation "maven.modrinth:ferrite-core:9.0.0-fabric"

    // Forge Config API Port
    implementation "maven.modrinth:forge-config-api-port:26.1.4"

    // ImmediatelyFast
    implementation "maven.modrinth:immediatelyfast:1.15.2+26.1.2-fabric"

    // Iris
    implementation "maven.modrinth:iris:1.10.9+26.1-fabric"

    // Ixeris
    implementation "maven.modrinth:ixeris:4.4.0+26.1.2-fabric"

    // LambDynamicLights
    implementation "maven.modrinth:lambdynamiclights:4.10.2+26.1.2"

    // Language Reload
    implementation "maven.modrinth:language-reload:1.7.6+26.1"

    // Lithium
    implementation "maven.modrinth:lithium:mc26.1.2-0.24.4-fabric"

    // Main Menu Credits
    implementation "maven.modrinth:main-menu-credits:1.3.0"

    // More Chat History
    implementation "maven.modrinth:morechathistory:2.0.0"

    // More Culling
    implementation "maven.modrinth:moreculling:1.7.0"

    // No Chat Reports
    implementation "maven.modrinth:no-chat-reports:Fabric-26.1-v2.19.0"

    // OptiGUI
    implementation "maven.modrinth:optigui:2.3.0-beta.10+26.1"

    // Paginated Advancements
    implementation "maven.modrinth:paginatedadvancements:2.8.0+26.1"

    // Puzzle
    implementation "maven.modrinth:puzzle:2.3.1+26.1-fabric"

    // Reese's Sodium Options
    implementation "maven.modrinth:reeses-sodium-options:mc26.1.1-2.0.5+fabric"

    // Remove Reloading Screen
    implementation "maven.modrinth:rrls:5.2.5+mc26.1"

    // Skyboxify
    implementation "maven.modrinth:skyboxify:R7DoQLx1"

    // Sodium
    implementation "maven.modrinth:sodium:mc26.1.2-0.8.12-fabric"

    // Sodium Extra
    implementation "maven.modrinth:sodium-extra:mc26.1.1-0.8.7+fabric"

    // Sodium Shadowy Path Blocks
    implementation "maven.modrinth:sodium-shadowy-path-blocks:7.0.0-fabric"

    // YetAnotherConfigLib
    implementation "maven.modrinth:yacl:3.9.3+26.1-fabric"

    // Zoomify
    implementation "maven.modrinth:zoomify:2.16.0+26.1"
}

loom {
    accessWidenerPath = file("src/main/resources/improvemymenus.classtweaker")
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    inputs.property "projectName", project.name

    from("LICENSE") {
        rename { "${it}_${project.name}"}
    }
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}